networks:
    eshop:

services:
  identity_service:
    container_name: eshop_identity_serice
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
        - KC_BOOTSTRAP_ADMIN_USERNAME=admin
        - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    hostname: keycloak
    ports:
        - "8080:8080"
    networks:
        - eshop
  sql_database:
    container_name: eshop_catalog_db
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
        - ACCEPT_EULA=y
        - MSSQL_SA_PASSWORD=$SQL_PASSWORD
    ports:
        - 1433:1433
    hostname: sql1
    networks:
        - eshop
  nosql_database:
    container_name: eshop_cart_db
    ports:
        - 27017:27017
    image: mongodb/mongodb-community-server:latest
    networks:
        - eshop
    hostname: nosql
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
        - ZOOKEEPER_CLIENT_PORT=2181
        - ZOOKEEPER_TICK_TIME=2000
    ports:
        - 22181:2181
    networks:
        - eshop
  kafka:
    container_name: eshop_kafka
    image: confluentinc/cp-kafka:latest
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
        - 9092:9092
    depends_on:
        - zookeeper
    networks:
        - eshop
    hostname: kafka
  eshop.catalogservice.api:
    container_name: catalog_service
    ports:
        - 7140:8081
        - 5265:5265
    build:
        context: ./eShop.CatalogService/.
        dockerfile: eShop.CatalogService.API/Dockerfile
    environment:
        - ConnectionStrings:DefaultConnection=data source=sql1,1433;initial catalog=TestDb;user id=sa;password=$SQL_PASSWORD;TrustServerCertificate=true
        - Authentication:Oidc:ClientSecret=$OIDC_CLIENT_SECRET
        - Kafka:BootstrapServers=kafka:9092
        - Authentication:Jwt:MetadataAddress=http://keycloak:8080/realms/eshop/.well-known/openid-configuration
        - Authentication:Jwt:Authority=http://keycloak:8080
        - ASPNETCORE_URLS=http://*:5265
    networks:
        - eshop
    depends_on:
        - sql_database
  eshop.cartservice.api:
    container_name: cart_service
    ports:
        - 8084:8084
    build:
        context: ./eShop.CartService/.
        dockerfile: eShop.CartService.API/Dockerfile
    environment:
        - MongoDB:ConnectionString=mongodb://nosql:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.4.2
        - MongoDB:DatabaseName=Carts
        - ASPNETCORE_URLS=http://*:8084
    networks:
        - eshop
    depends_on:
        - nosql_database
  eshop.cartservice.console:
    container_name: kafka_reader
    build:
        context: ./eShop.CartService/.
        dockerfile: eShop.CartService.Console/Dockerfile
    environment:
        - MongoDB:ConnectionString=mongodb://nosql:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.4.2
        - MongoDB:DatabaseName=Carts
        - Kafka:BootstrapServers=kafka:9092
    depends_on:
        - kafka
    networks:
        - eshop
    